:Author: duleorlovic
:Email:
:Date: 18/11/2022
:Revision: version#
:License: Public Domain

= Project: {Project}

Start machine for water races. Simply pull and release the rope.

== Step 1: Installation

Read `git log` to see how the code is generated.

Create new blank project.
Add two variables `relay_up` and `relay_down`.
Attach new device with name *nodeMCU* and save DEVICE_ID (used as
`DEVICE_LOGIN_NAME`) and *SECRET_KEY* (used as `SECRET_DEVICE_KEY`).
Add secrets for network and device by
```
cp arduino_secrets.h.template arduino_secrets.h
vi arduino_secrets.h
# update SECRET_SSID=trk, SECRET_OPTIONAL_PASS=wifipass and SECRET_DEVICE_KEY=123
```

== Step 2: Assemble the circuit

Assemble the circuit following the diagram ./wiring_relays_schematic.jpeg

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact: 

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name      | Part number | Quantity
| R1 | 10k Resistor   | 1234-abcd   | 10       
| L1 | Red LED        | 2345-asdf   | 5        
| A1 | Arduino Zero   | ABX00066    | 1        
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
