// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

void onRelayDownChange();
void onRelayUpChange();

bool relay_down;
bool relay_up;

void initProperties(){

  ArduinoCloud.addProperty(relay_down, READWRITE, ON_CHANGE, onRelayDownChange);
  ArduinoCloud.addProperty(relay_up, READWRITE, ON_CHANGE, onRelayUpChange);

}

////////////////////////////ATTENTION!!!////////////////////////////////
// ATTENTION: No device is currently associated to this Thing,        //
// hence the Connection Handler code could not be generated           //
// Please associate an existing or new device or manually create your //
// instance of Connection Handler                                     //
// Eg.                                                                // 
// WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);   //
////////////////////////////////////////////////////////////////////////

#error "No device is currently associated to this Thing, hence the Connection Handler code could not be generated"
